.DEFAULT_GOAL := default
default: all

GIT_COMMIT ?= $(shell git rev-parse --short "HEAD^{commit}" 2>/dev/null)
GIT_VERSION ?= $(shell git describe --long --tags --abbrev=7 --match 'v[0-9]*' --dirty 2>/dev/null || echo 'v0.0.0-unknown-$(GIT_COMMIT)')
BUILD_DATE ?= $(shell date -u +'%Y-%m-%dT%H:%M:%SZ')

BIN_DIR := $(CURDIR)/bin
CONTAINER_ENGINE ?= $(shell which podman 2>/dev/null || which docker 2>/dev/null)
GO ?= go

# Ensure bin directory exists
$(BIN_DIR):
	mkdir -p $(BIN_DIR)

# Build ldflags for version injection
LDFLAGS := -X github.com/stolostron/multicluster-mesh-addon/pkg/version.versionFromGit=$(GIT_VERSION)
LDFLAGS += -X github.com/stolostron/multicluster-mesh-addon/pkg/version.commitFromGit=$(GIT_COMMIT)
LDFLAGS += -X github.com/stolostron/multicluster-mesh-addon/pkg/version.buildDate=$(BUILD_DATE)

# Go 1.24 tool handling, from the cache; the double invocation will be fixed in 1.25
# See https://github.com/golang/go/issues/72824
gotool = $(shell $(GO) -C $(1) tool -n $(2) > /dev/null && $(GO) -C $(1) tool -n $(2))

GOLANGCI_LINT ?= $(call gotool,tools,golangci-lint)
CONTROLLER_GEN = $(call gotool,tools,controller-gen)

# Test variables
CONTROLLER_RUNTIME_BRANCH ?= release-0.23
ENVTEST_K8S_VERSION ?= 1.35
ENVTEST ?= $(BIN_DIR)/setup-envtest
TEST_CRD_DIR := $(CURDIR)/test/integration/crds

$(ENVTEST): $(BIN_DIR)
	@test -s $(ENVTEST) || GOBIN=$(BIN_DIR) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@$(CONTROLLER_RUNTIME_BRANCH)

HELM_VERSION ?= v4.2.2
HELM_BIN := $(BIN_DIR)/helm
HELM ?= $(shell which helm 2>/dev/null || echo $(HELM_BIN))
CHART_DIR := $(CURDIR)/chart
HELM_RELEASE_NAME ?= multicluster-mesh-addon
ADDON_NAMESPACE ?= multicluster-mesh-system

OS := $(shell go env GOOS)
ARCH := $(shell go env GOARCH)

$(HELM_BIN): $(BIN_DIR)
	@if test -x $(HELM_BIN) && $(HELM_BIN) version --short 2>/dev/null | grep -q $(HELM_VERSION); then \
		echo "helm $(HELM_VERSION) already installed"; \
	else \
		echo "Installing helm $(HELM_VERSION)..."; \
		tmp_dir=$$(mktemp -d); \
		curl -sSL https://get.helm.sh/helm-$(HELM_VERSION)-$(OS)-$(ARCH).tar.gz -o $$tmp_dir/helm.tar.gz; \
		tar xzf $$tmp_dir/helm.tar.gz -C $$tmp_dir; \
		mv $$tmp_dir/$(OS)-$(ARCH)/helm $(HELM_BIN); \
		chmod +x $(HELM_BIN); \
		rm -rf $$tmp_dir; \
	fi

# Image registry and name
# TODO: Change REGISTRY_BASE back to quay.io/stolostron when we have access to that registry
REGISTRY_BASE ?= quay.io/sail-dev
IMG ?= $(REGISTRY_BASE)/multicluster-mesh-addon:$(GIT_VERSION)

# PLATFORM selects the Helm values file to use. Supported values: openshift, kind
PLATFORM ?= openshift
VALID_PLATFORMS := openshift kind
ifeq ($(filter $(PLATFORM),$(VALID_PLATFORMS)),)
$(error PLATFORM must be one of: $(VALID_PLATFORMS))
endif

.PHONY: deps
deps: go.mod go.sum
	go mod tidy
	go mod download
	go mod verify

.PHONY: fmt
fmt: ## Format Go code
	go fmt ./...

.PHONY: gen-code
gen-code: ## Generate DeepCopy code
	$(CONTROLLER_GEN) object paths=./pkg/apis/...

.PHONY: gen-crds
gen-crds: ## Generate CRD manifests
	$(CONTROLLER_GEN) crd paths=./pkg/apis/... output:crd:dir=./chart/crds

.PHONY: gen-rbac
gen-rbac: ## Generate RBAC manifests from controller annotations
	$(CONTROLLER_GEN) rbac:roleName=multicluster-mesh-controller paths=./pkg/hub/mesh output:rbac:dir=/tmp
	@printf '# Generated by make gen-rbac from kubebuilder annotations in pkg/hub/mesh/controller.go\n# Do not edit manually - run make gen-rbac to regenerate\n' | cat - /tmp/role.yaml > $(CHART_DIR)/templates/clusterrole.yaml

.PHONY: gen
gen: gen-code gen-crds gen-rbac ## Generate code, CRDs, and RBAC

.PHONY: verify-gen
verify-gen: gen ## Verify generated files are up to date
	@if ! git diff --quiet HEAD -- chart/crds/ chart/templates/clusterrole.yaml pkg/apis/**/zz_generated.*.go; then \
		echo "Generated files are out of date. Stage and commit the changes shown below."; \
		git diff --stat HEAD; \
		exit 1; \
	fi

.PHONY: vet
vet: ## Run go vet
	go vet ./...

.PHONY: verify
verify: verify-gofmt verify-modules verify-gen vet ## Run all checks (may regenerate files)

.PHONY: verify-gofmt
verify-gofmt: ## Verify code is formatted correctly
	@echo "Verifying gofmt..."
	@test -z "$$(gofmt -s -l . | grep -v zz_generated)" || (echo "Code not formatted, run 'make fmt'" && exit 1)

.PHONY: verify-modules
verify-modules: ## Verify go modules are up to date
	@echo "Verifying go modules..."
	@go mod tidy -diff || (echo "ERROR: go.mod/go.sum are out of date. Run 'go mod tidy'" && exit 1)

.PHONY: golangci-lint
golangci-lint: ## Run golangci-lint
	$(GOLANGCI_LINT) run --timeout=5m ./...

.PHONY: test
test: ## Run unit tests
	go test -short ./pkg/...

.PHONY: update-test-crds
update-test-crds: deps ## Update test CRDs from OCM API, managed-serviceaccount and cert-manager dependencies
	@echo "Updating test CRDs from open-cluster-management.io/api..."
	@set -e; \
	OCM_API_PATH=$$(go list -m -f '{{.Dir}}' open-cluster-management.io/api); \
	mkdir -p $(TEST_CRD_DIR)/ocm; \
	echo "Copying CRDs from $$OCM_API_PATH..."; \
	cp -v $$OCM_API_PATH/cluster/v1/*.crd.yaml $(TEST_CRD_DIR)/ocm/ 2>/dev/null || true; \
	cp -v $$OCM_API_PATH/cluster/v1beta2/*.crd.yaml $(TEST_CRD_DIR)/ocm/ 2>/dev/null || true; \
	cp -v $$OCM_API_PATH/work/v1/*.crd.yaml $(TEST_CRD_DIR)/ocm/ 2>/dev/null || true; \
	echo "Test CRDs updated successfully in $(TEST_CRD_DIR)/ocm/"
	@echo "Updating test CRDs from open-cluster-management.io/managed-serviceaccount..."
	@set -e; \
	OCM_MSA_PATH=$$(go list -m -f '{{.Dir}}' open-cluster-management.io/managed-serviceaccount); \
	echo "Copying CRDs from $$OCM_MSA_PATH..."; \
	cp -v $$OCM_MSA_PATH/charts/managed-serviceaccount/crds/*.yaml $(TEST_CRD_DIR)/ocm/; \
	echo "Test CRDs for MSA updated successfully in $(TEST_CRD_DIR)/ocm/"
	@echo "Updating test CRDs from cert-manager..."
	@set -e; \
	CERTMANAGER_PATH=$$(go list -m -f '{{.Dir}}' github.com/cert-manager/cert-manager); \
	mkdir -p $(TEST_CRD_DIR)/cert-manager; \
	echo "Copying CRDs from $$CERTMANAGER_PATH..."; \
	cp -v $$CERTMANAGER_PATH/deploy/crds/cert-manager.io_certificates.yaml $(TEST_CRD_DIR)/cert-manager/ 2>/dev/null || true; \
	cp -v $$CERTMANAGER_PATH/deploy/crds/cert-manager.io_issuers.yaml $(TEST_CRD_DIR)/cert-manager/ 2>/dev/null || true; \
	echo "Test CRDs updated successfully in $(TEST_CRD_DIR)/cert-manager/"

.PHONY: test-integration
test-integration: $(ENVTEST) gen-crds deps update-test-crds ## Run integration tests
	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)" \
	go run github.com/onsi/ginkgo/v2/ginkgo -v --tags=integration ./test/integration/...

.PHONY: test-e2e
test-e2e: ## Run e2e tests against dev-env clusters (requires make dev-env)
	HUB_KUBECONFIG=$(HUB_KUBECONFIG) \
	CLUSTER1_KUBECONFIG=$(DEV_KUBE_DIR)/cluster1.config \
	CLUSTER2_KUBECONFIG=$(DEV_KUBE_DIR)/cluster2.config \
	go run github.com/onsi/ginkgo/v2/ginkgo -v --fail-fast --tags=e2e ./test/e2e/...

.PHONY: build
build: $(BIN_DIR) ## Build addon binary
	CGO_ENABLED=0 go build -buildvcs=false -ldflags "$(LDFLAGS)" -o $(BIN_DIR)/multicluster-mesh-addon .

.PHONY: all
all: build test

.PHONY: clean
clean: ## Clean build artifacts
	rm -rf $(BIN_DIR)

.PHONY: images
images: ## Build the container image
	$(CONTAINER_ENGINE) build -t $(IMG) .


.PHONY: push
push: images ## Push the container image
	$(CONTAINER_ENGINE) push $(IMG)

.PHONY: deploy
deploy: gen push $(HELM_BIN) ## Deploy the controller using Helm (PLATFORM=openshift|kind)
	$(HELM) upgrade --install $(HELM_RELEASE_NAME) $(CHART_DIR) \
		--create-namespace \
		--namespace $(ADDON_NAMESPACE) \
		--set image.repository=$(REGISTRY_BASE)/multicluster-mesh-addon \
		--set image.tag=$(GIT_VERSION) \
		$(if $(filter kind,$(PLATFORM)),--set platform=kind --set image.pullPolicy=IfNotPresent) \
		--wait --timeout 180s

.PHONY: undeploy
undeploy: $(HELM_BIN) ## Remove the controller using Helm
	kubectl delete multiclustermeshes.mesh.open-cluster-management.io --all --all-namespaces --ignore-not-found=true || true
	$(HELM) uninstall $(HELM_RELEASE_NAME) --namespace $(ADDON_NAMESPACE) || true
	kubectl delete crd multiclustermeshes.mesh.open-cluster-management.io --ignore-not-found=true

.PHONY: helm-lint
helm-lint: $(HELM_BIN) ## Lint Helm chart
	$(HELM) lint $(CHART_DIR)


.PHONY: help
help: ## Display this help
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

# Dev Environment (local Kind + OCM clusters)
KIND_VERSION ?= v0.31.0
CLUSTERADM_VERSION ?= v1.3.1
K8S_VERSION ?= v1.35.0
OLM_VERSION ?= v0.43.0
CERT_MANAGER_VERSION ?= v1.20.2
MSA_VERSION ?= 0.10.0

DEV_KUBE_DIR := $(CURDIR)/.kube
HUB_KUBECONFIG := $(DEV_KUBE_DIR)/hub.config

KIND := $(BIN_DIR)/kind
CLUSTERADM := $(BIN_DIR)/clusteradm

$(KIND): | $(BIN_DIR)
	@if test -x $(KIND) && $(KIND) version 2>/dev/null | grep -q $(KIND_VERSION); then \
		echo "kind $(KIND_VERSION) already installed"; \
	else \
		echo "Installing kind $(KIND_VERSION)..."; \
		curl -sSL https://github.com/kubernetes-sigs/kind/releases/download/$(KIND_VERSION)/kind-$(OS)-$(ARCH) -o $(KIND); \
		chmod +x $(KIND); \
	fi

$(CLUSTERADM): | $(BIN_DIR)
	@if test -x $(CLUSTERADM) && $(CLUSTERADM) version 2>/dev/null | grep -q $(CLUSTERADM_VERSION); then \
		echo "clusteradm $(CLUSTERADM_VERSION) already installed"; \
	else \
		echo "Installing clusteradm $(CLUSTERADM_VERSION)..."; \
		tmp_dir=$$(mktemp -d); \
		curl -sSL https://github.com/open-cluster-management-io/clusteradm/releases/download/$(CLUSTERADM_VERSION)/clusteradm_$(OS)_$(ARCH).tar.gz -o $$tmp_dir/clusteradm.tar.gz; \
		tar xzf $$tmp_dir/clusteradm.tar.gz -C $$tmp_dir; \
		mv $$tmp_dir/clusteradm $(CLUSTERADM); \
		chmod +x $(CLUSTERADM); \
		rm -rf $$tmp_dir; \
	fi

DEV_ENV_SCRIPT := $(CURDIR)/hack/dev-env.sh

export DEV_KUBE_DIR K8S_VERSION OLM_VERSION CERT_MANAGER_VERSION MSA_VERSION
export KIND CLUSTERADM HELM

.PHONY: dev-env
dev-env: create-clusters install-olm install-cert-manager init-ocm join-clusters install-managed-serviceaccount deploy-addon ## Provision full dev environment (Kind + OCM + addon)

.PHONY: create-clusters
create-clusters: $(KIND) ## Create 3 Kind clusters (hub, cluster1, cluster2)
	$(DEV_ENV_SCRIPT) create-clusters

.PHONY: install-olm
install-olm: ## Install OLM on managed clusters (cluster1, cluster2)
	$(DEV_ENV_SCRIPT) install-olm

.PHONY: install-cert-manager
install-cert-manager: ## Install cert-manager on the hub cluster
	$(DEV_ENV_SCRIPT) install-cert-manager

.PHONY: init-ocm
init-ocm: $(CLUSTERADM) ## Initialize hub as OCM control plane
	$(DEV_ENV_SCRIPT) init-ocm

.PHONY: join-clusters
join-clusters: $(CLUSTERADM) ## Register managed clusters and create ManagedClusterSet
	$(DEV_ENV_SCRIPT) join-clusters

.PHONY: install-managed-serviceaccount
install-managed-serviceaccount: $(HELM_BIN) ## Install managed-serviceaccount addon to the hub cluster
	$(DEV_ENV_SCRIPT) install-managed-serviceaccount

.PHONY: deploy-addon
deploy-addon: $(KIND) $(HELM_BIN) gen images ## Build and deploy addon to the hub Kind cluster
	# We use image-archive instead of docker-image because the latter is Docker-specific
	# and fails when images are built with Podman (separate image stores).
	$(CONTAINER_ENGINE) save $(IMG) -o $(DEV_KUBE_DIR)/.addon-image.tar
	$(KIND) load image-archive $(DEV_KUBE_DIR)/.addon-image.tar --name hub
	rm -f $(DEV_KUBE_DIR)/.addon-image.tar
	$(HELM) upgrade --install $(HELM_RELEASE_NAME) $(CHART_DIR) \
		--kubeconfig=$(HUB_KUBECONFIG) \
		--create-namespace \
		--namespace $(ADDON_NAMESPACE) \
		--set platform=kind \
		--set image.pullPolicy=IfNotPresent \
		--set image.repository=$(REGISTRY_BASE)/multicluster-mesh-addon \
		--set image.tag=$(GIT_VERSION) \
		--wait --timeout 180s
	kubectl --kubeconfig=$(HUB_KUBECONFIG) rollout status deployment/multicluster-mesh-controller \
		-n $(ADDON_NAMESPACE) --timeout=180s
	@echo "==> Addon controller deployed successfully. Use KUBECONFIG=$(HUB_KUBECONFIG) to interact with the hub."

.PHONY: setup-mesh
setup-mesh: ## Create cert-manager trust chain, mesh-system namespace, and MultiClusterMesh CR
	$(DEV_ENV_SCRIPT) setup-mesh

.PHONY: dev-clean-meshes
dev-clean-meshes: ## Delete all mesh resources, cert-manager trust chain, and mesh-system namespace
	kubectl --kubeconfig=$(HUB_KUBECONFIG) delete multiclustermeshes -A --all --ignore-not-found=true
	kubectl --kubeconfig=$(HUB_KUBECONFIG) delete manifestwork -A -l app.kubernetes.io/managed-by=multicluster-mesh-addon --ignore-not-found=true
	kubectl --kubeconfig=$(HUB_KUBECONFIG) delete namespace mesh-system --ignore-not-found=true

.PHONY: dev-clean
dev-clean: ## Destroy dev clusters and remove .kube/ folder
	$(DEV_ENV_SCRIPT) clean
