apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: ossm-acm
spec:
  displayName: OpenShift Service Mesh — ACM Integration
  backend:
    type: Service
    service:
      name: ossm-acm-plugin
      namespace: ossm-acm-plugin
      port: 9443
      basePath: /
