worker_processes auto;
error_log /dev/stderr;
pid /tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout;

  client_body_temp_path /tmp/client_body;
  proxy_temp_path /tmp/proxy;
  fastcgi_temp_path /tmp/fastcgi;
  uwsgi_temp_path /tmp/uwsgi;
  scgi_temp_path /tmp/scgi;

  server {
    listen 9443 ssl;
    root /usr/share/nginx/html;

    ssl_certificate /var/serving-cert/tls.crt;
    ssl_certificate_key /var/serving-cert/tls.key;

    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods "GET, OPTIONS";
    add_header Access-Control-Allow-Headers "Content-Type";

    location / {
      try_files $uri =404;
    }
  }
}
