/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/stolostron/multicluster-mesh-addon/apis/mesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMeshDeployments implements MeshDeploymentInterface
type FakeMeshDeployments struct {
	Fake *FakeMeshV1alpha1
	ns   string
}

var meshdeploymentsResource = schema.GroupVersionResource{Group: "mesh.open-cluster-management.io", Version: "v1alpha1", Resource: "meshdeployments"}

var meshdeploymentsKind = schema.GroupVersionKind{Group: "mesh.open-cluster-management.io", Version: "v1alpha1", Kind: "MeshDeployment"}

// Get takes name of the meshDeployment, and returns the corresponding meshDeployment object, and an error if there is any.
func (c *FakeMeshDeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MeshDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(meshdeploymentsResource, c.ns, name), &v1alpha1.MeshDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshDeployment), err
}

// List takes label and field selectors, and returns the list of MeshDeployments that match those selectors.
func (c *FakeMeshDeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MeshDeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(meshdeploymentsResource, meshdeploymentsKind, c.ns, opts), &v1alpha1.MeshDeploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MeshDeploymentList{ListMeta: obj.(*v1alpha1.MeshDeploymentList).ListMeta}
	for _, item := range obj.(*v1alpha1.MeshDeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested meshDeployments.
func (c *FakeMeshDeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(meshdeploymentsResource, c.ns, opts))

}

// Create takes the representation of a meshDeployment and creates it.  Returns the server's representation of the meshDeployment, and an error, if there is any.
func (c *FakeMeshDeployments) Create(ctx context.Context, meshDeployment *v1alpha1.MeshDeployment, opts v1.CreateOptions) (result *v1alpha1.MeshDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(meshdeploymentsResource, c.ns, meshDeployment), &v1alpha1.MeshDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshDeployment), err
}

// Update takes the representation of a meshDeployment and updates it. Returns the server's representation of the meshDeployment, and an error, if there is any.
func (c *FakeMeshDeployments) Update(ctx context.Context, meshDeployment *v1alpha1.MeshDeployment, opts v1.UpdateOptions) (result *v1alpha1.MeshDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(meshdeploymentsResource, c.ns, meshDeployment), &v1alpha1.MeshDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshDeployment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMeshDeployments) UpdateStatus(ctx context.Context, meshDeployment *v1alpha1.MeshDeployment, opts v1.UpdateOptions) (*v1alpha1.MeshDeployment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(meshdeploymentsResource, "status", c.ns, meshDeployment), &v1alpha1.MeshDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshDeployment), err
}

// Delete takes name of the meshDeployment and deletes it. Returns an error if one occurs.
func (c *FakeMeshDeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(meshdeploymentsResource, c.ns, name, opts), &v1alpha1.MeshDeployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMeshDeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(meshdeploymentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MeshDeploymentList{})
	return err
}

// Patch applies the patch and returns the patched meshDeployment.
func (c *FakeMeshDeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MeshDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(meshdeploymentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MeshDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshDeployment), err
}
