/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	scheme "github.com/stolostron/multicluster-mesh-addon/apis/client/clientset/versioned/scheme"
	v1alpha1 "github.com/stolostron/multicluster-mesh-addon/apis/mesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MeshDeploymentsGetter has a method to return a MeshDeploymentInterface.
// A group's client should implement this interface.
type MeshDeploymentsGetter interface {
	MeshDeployments(namespace string) MeshDeploymentInterface
}

// MeshDeploymentInterface has methods to work with MeshDeployment resources.
type MeshDeploymentInterface interface {
	Create(ctx context.Context, meshDeployment *v1alpha1.MeshDeployment, opts v1.CreateOptions) (*v1alpha1.MeshDeployment, error)
	Update(ctx context.Context, meshDeployment *v1alpha1.MeshDeployment, opts v1.UpdateOptions) (*v1alpha1.MeshDeployment, error)
	UpdateStatus(ctx context.Context, meshDeployment *v1alpha1.MeshDeployment, opts v1.UpdateOptions) (*v1alpha1.MeshDeployment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MeshDeployment, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MeshDeploymentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MeshDeployment, err error)
	MeshDeploymentExpansion
}

// meshDeployments implements MeshDeploymentInterface
type meshDeployments struct {
	client rest.Interface
	ns     string
}

// newMeshDeployments returns a MeshDeployments
func newMeshDeployments(c *MeshV1alpha1Client, namespace string) *meshDeployments {
	return &meshDeployments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the meshDeployment, and returns the corresponding meshDeployment object, and an error if there is any.
func (c *meshDeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MeshDeployment, err error) {
	result = &v1alpha1.MeshDeployment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("meshdeployments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MeshDeployments that match those selectors.
func (c *meshDeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MeshDeploymentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MeshDeploymentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("meshdeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested meshDeployments.
func (c *meshDeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("meshdeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a meshDeployment and creates it.  Returns the server's representation of the meshDeployment, and an error, if there is any.
func (c *meshDeployments) Create(ctx context.Context, meshDeployment *v1alpha1.MeshDeployment, opts v1.CreateOptions) (result *v1alpha1.MeshDeployment, err error) {
	result = &v1alpha1.MeshDeployment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("meshdeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(meshDeployment).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a meshDeployment and updates it. Returns the server's representation of the meshDeployment, and an error, if there is any.
func (c *meshDeployments) Update(ctx context.Context, meshDeployment *v1alpha1.MeshDeployment, opts v1.UpdateOptions) (result *v1alpha1.MeshDeployment, err error) {
	result = &v1alpha1.MeshDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("meshdeployments").
		Name(meshDeployment.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(meshDeployment).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *meshDeployments) UpdateStatus(ctx context.Context, meshDeployment *v1alpha1.MeshDeployment, opts v1.UpdateOptions) (result *v1alpha1.MeshDeployment, err error) {
	result = &v1alpha1.MeshDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("meshdeployments").
		Name(meshDeployment.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(meshDeployment).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the meshDeployment and deletes it. Returns an error if one occurs.
func (c *meshDeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("meshdeployments").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *meshDeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("meshdeployments").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched meshDeployment.
func (c *meshDeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MeshDeployment, err error) {
	result = &v1alpha1.MeshDeployment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("meshdeployments").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
